export const Images = {
  appLogo: require('../assets/images/appLogo.png'),
  hidePasswordIcon: require('../assets/images/hidePasswordIcon.png'),
  goBack: require('../assets/images/goBack.png'),
  rightThemeArrow: require('../assets/images/rightThemeArrow.png'),
  dropDownArrow: require('../assets/images/dropDownArrow.png'),
  whiteDownArrow: require('../assets/images/whiteDownArrow.png'),
  activeBellIcon: require('../assets/images/activeBellIcon.png'),
  nonActiveNotificationIcon: require('../assets/images/nonActiveNotificationIcon.png'),
  locationMarkIcon: require('../assets/images/locationMarkIcon.png'),
  settingDots: require('../assets/images/settingDots.png'),
  profile: require('../assets/images/profile.png'),
  calendar: require('../assets/images/calendar.png'),
  totalHours: require('../assets/images/totalHours.png'),
  absentHours: require('../assets/images/absentHours.png'),
  presentHours: require('../assets/images/presentHours.png'),
  lateHours: require('../assets/images/lateHours.png'),
  policySecureIcon: require('../assets/images/policySecureIcon.png'),
  personCalendar: require('../assets/images/personCalendar.png'),
  searchIcon: require('../assets/images/searchIcon.png'),
  addIcon: require('../assets/images/addIcon.png'),
};
