export const Labels = {
  // Common
  appName: 'RN APP NAME',
  ///// Input fields Labels and Suggestions notes
  enterEmail: 'please enter email',
  emailIsRequired: 'Email is required',
  phoneNumberIsRequired: 'phone number is required',
  insuranceProviderIsRequired: 'insurance provider is required',
  genderIsRequired: 'gender is required',
  cityIsRequired: 'city is required',
  invalidEmail: 'Email is invalid',
  invalidPhoneNumber: 'invalid phone number',
  invalidCity: 'invalid city',
  address: 'Address',
  dateOfBirth: 'Date of Birth',
  password: 'password',
  oldPassword: 'old password',
  // newPassword: 'new password',
  passwordKey: 'password',
  newPasswordKey: 'newPassword',
  passwordIsRequired: 'Password is required',
  invalidPassword: 'Password is invalid',
  confirmPassword: 'confirm password',
  // confirmNewPassword: 'confirm new password',
  confirmPasswordRequired: 'confirm password is required ',
  currentPassword: 'Current Password',
  placeholderCurrentPassword: 'Enter your Current Password',
  newPassword: 'New Password',
  placeholderNewPassword: 'Enter your New Password',
  confirmNewPassword: 'Confirm New Password',
  placeholderConfirmNewPassword: 'Enter your Confirm New Password',
  otpCodeIsRequired: 'otp code is required',
  confirmPasswordKey: 'confirmPassword',
  confirmNewPasswordKey: 'confirmNewPassword',
  invalidConfirmPassword: 'confirm password is invalid',
  passwordSuggestion:
    'minumum length of password must be 8 characters, at least one uppercase letter, one lowercase letter,one special character and one number',
  passwordsDontMatch: "passwords don't match",
  fullName: 'full name',
  fullNameKey: 'fullName',
  fullNameIsRequired: 'full name is required',
  firstNameIsRequired: 'first name is required',
  lastNameIsRequired: 'last name is required',
  userNameIsRequired: 'user name is required',
  invalidFullName: 'full name is invalid',
  invalidFirstName: 'first name is invalid',
  invalidlasttName: 'last name is invalid',
  invalidUserName: 'invalid user name',
  codeIsRequired: 'code is required',
  insuranceProvider: 'Insurance Provider',
  ////////////////////////////////////////////////////////////////
  signIn: 'Sign In',
  signInToYourAccount: 'Sign in to your account',
  signInWelcomeNote: `Sign welcome note here...`,
  detailText:
    'The Monitoring Unit – HEALTH is a centralized platform designed to track, evaluate, and enhance healthcare services through real-time data analysis, ensuring transparency, accountability, and continuous improvement across all levels of the health system.',
  forgotPassword: 'Forgot Password',
  forgotYourPassword: 'Forgot your password?',
  forgotPasswordNote: `We want to make sure it's really you. In order to further verify you identity, please enter your regesterd email address.`,
  recentDuties: 'Recent Duties',
  seeAll: 'See all',
  search: 'Search',
  all: 'All',
  menu: 'Menu',
  uploadForm: 'Upload Form',
  feedBack: 'Feedback',
  formQuestions: 'Form Questions',
  profile: 'Profile',
  profileDetails: 'Profile Details',
  notification: 'Notification',
  salarSlip: 'Salary Slip',
  attendance: 'Attendance',
  editProfile: 'Edit Profile',
  downloadRoaster: 'Download Roaster ',
  changePassword: 'Change Password',
  save: 'Save',
  send: 'Send',
  enterFeedback: 'Please Enter Your Feedback ',
  reason: 'Reason',
  selectType: 'Select Type',
  sendCode: 'Send Code',
  codeWillExpire: 'Code will expire in 5 minutes',
  otpVerification: 'OTP Code Verification',
  codeErrorNote:
    'if you have recieved an error, simply ignore this email and do not click the button.',
  otpNote: `We have sent you code to your regesterd email address. Enter the OTP code below to create new password.`,
  otpErrorNote: 'The code you entered is either incorrect or expired.',
  didntReceiveEmail: `Didn't receive email?`,
  resendCodeNote: 'We can resend code in 53 seconds',
  fromDate: 'From Date',
  toDate: 'To Date',
  employeeId: 'Employee ID',
  department: 'Department',
  createdOn: 'Created On',
  preparedBy: 'Prepared By',
  policy: 'Policy',
  leaveManagement: 'Leave Management',
  leaveType: 'Leave Type:',
  ///////////
  DemographicDetails: {
    title: 'Demographic Detail',
    so: 'S/O',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    maritalStatus: 'Marital Status',
    religion: 'Religion',
    phoneNo: 'Phone No',
    emergencyNo: 'Emergency No',
    cnic: 'CNIC',
    cnicIssuance: 'CNIC Issuance',
    cnicExpiry: 'CNIC Expiry',
    personalEmail: 'Personal Email',
    officialEmail: 'Official Email',
    bloodGroup: 'Blood Group',
    exemptedFromAttendance: 'Exempted From Attendance',
    timeSheetRequired: 'Time Sheet Required',
    district: 'District',
    residentialAddress: 'Residential Address',
    permanentAddress: 'Permanent Address',
  },
  JobDetails: {
    title: 'Job Detail',
    headOffice: 'Head Office',
    branchOffice: 'Branch Office',
    designation: 'Designation',
    reportTo: 'Report To',
    department: 'Department',
    employeeType: 'Employee Type',
    shift: 'Shift',
    referenceType: 'Reference Type',
    grade: 'Grade',
  },
  leaveDetails: {
    title: 'Leave Detail',
    employeeName: 'Employee Name',
    department: 'Department',
    leaveType: 'Leave Type',
    startDate: 'Start Date',
    endDate: 'End Date',
    days: 'Days',
    leavePaidStatus: 'Leave Paid Status',
    reason: 'Reason',
  },
  status: 'Status:',
  approved: 'Approved',
  dayType: 'Full Day / Half Day',
};
